#######################################
# Configuration file for dync-server
#######################################

# TODO we have to check if this directive will be necessary
options:
    pidfile: /path/to/pidfile
    umask: 0077  # umask for all output files


# The address and tcp port where the server listens for incoming messages
# Default is 'tcp://*:8889'
address: "tcp://*:8889"

# Directions for redirecting uploaded files
storage:
    tmp_dir: /path/to/temp/storage # Location for temporary file upload storage
    path: /path/to/default/storage # The default storage location
    manual: /path/to/manual        # files that need to be processed manually
    storage: /path/to/storage      # backup of files, project-wise sorting
    dropboxes:
       - regexp: "(.|\\n)*\\.pdf$"
         path: "/tmp/dataserv/pdf"
         origin: ["sfillinger"]


# See https://docs.python.org/2/library/logging.config.html
logging:
    version: 1
    disable_existing_loggers: False
    root:
        level: NOTSET
        handlers: ['file', 'console']
    handlers:
        file:
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: detailed
            filename: dync-server.log
            mode: a
            maxBytes: 10485760
            backupCount: 5
        console:
            class: logging.StreamHandler
            level: ERROR
            formatter: detailed
    formatters:
        detailed:
            format: '%(asctime)s %(module)-17s line:%(lineno)-4d (levelname)-8s %(message)s'
        email:
            format: 'Timestamp: %(asctime)s\nModule: %(module)s\n Line: %(lineno)d\nMessage: %(message)s'
