#######################################
# Configuration file for dync-server
#######################################

# TODO we have to check if this directive will be necessary
options:
    permissions: true
    checksum: true
    interval: 30
    pidfile: /path/to/pidfile
    umask: 0077  # umask for all output files


outgoing:
    manual: /path/to/manual/dest  # files that need to be processed manually
    storage: /path/to/storage     # backup of files, project-wise sorting
    tmpdir: /path/to/tmpdir       # temp dir prefix for the upload


# filenames are cleaned before they are matched against the regexps.
# They are alphanumeric and start with a barcode. Extensions are
# lower case. If more than one regexp matches a filename, only the
# first match is used.
#
# Backslashes must be escaped.
openbis:
   - regexp: "^\\w*.raw$"
     path: /path/to/raw/dropbox
     match_file: True
     match_dir: False  # do not match incoming directories
     origin: ['dropbox1']  # only match files from these dropboxes
   - regexp: "^\\w*.fastq$"
     path: /path/to/fastq/dropbox

# See https://docs.python.org/2/library/logging.config.html
logging:
    version: 1
    disable_existing_loggers: False
    root:
        level: NOTSET
        handlers: ['file', 'console']
    handlers:
        file:
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: detailed
            filename: dync-server.log
            mode: a
            maxBytes: 10485760
            backupCount: 5
        console:
            class: logging.StreamHandler
            level: ERROR
            formatter: detailed
    formatters:
        detailed:
            format: '%(asctime)s %(module)-17s line:%(lineno)-4d (levelname)-8s %(message)s'
        email:
            format: 'Timestamp: %(asctime)s\nModule: %(module)s\n Line: %(lineno)d\nMessage: %(message)s'
